[package]
name = "quassel-dump-all"
version = "0.1.1"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
regex = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
rusqlite = { version = "0.32", features = ["bundled"] }
postgres = "0.19"
rpassword = "7"
